apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
    role: canary
  name: sample-app-canary
  namespace: test
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: sample-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: susantez/sample-app-v1.0.1 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080 # The port that the container is running on in the cluster
              protocol: TCP