apiVersion: v1
kind: Service
metadata:
  name: sample-app
  labels:
    app: sample-app
    service: sample-app
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: sample-app
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: sample-app-v1
  labels:
    app: sample-app
    version: v1
spec:
  replicas: 2 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: sample-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-app
        version: v1
    spec:
      containers:
        - name: sample-app
          image: susantez/sample-app-v1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080 # The port that the container is running on in the cluster
              protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app-v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 99