apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: sample-app
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: sample-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: susantez/sample-app-v1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080 # The port that the container is running on in the cluster
              protocol: TCP
            - name: http-metrics
              containerPort: 9797 # The port that the http-metrics served
              protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # scale up if usage is above
          # 99% of the requested CPU (100m)
          averageUtilization: 99